Repository reasonml/reason-react, pull requests merged in 2020-04, with the labels that each got.

#364 Add onInvalid
  src/ReactDOMRe.re
Labels: enhancement

#424 ReasonReactCompat docs
  docs/jsx.md
  docs/reasonreactcompat.md
  website/sidebars.json
Labels: docs

#323 Update invalid-prop-name.md
  docs/invalid-prop-name.md
Labels: docs

#341 Fix errors in the example of instance variables documentation
  docs/instance-variables.md
Labels: docs

#495 docs(context-mixins): binding to external Context
  docs/context-mixins.md
Labels: docs

#532 Update Examples based off React.js Docs and Reorganize a bit
  docs/counter.md
  docs/gentype.md
  docs/importing-js-into-reason.md
  docs/importing-reason-into-js.md
  docs/render-props.md
  docs/simple.md
  docs/use-state-use-effect.md
  docs/usedebounce-custom-hook.md
  docs/useeffect-hook.md
  docs/usereducer-hook.md
  docs/usestate-hook.md
  website/i18n/en.json
  website/sidebars.json
Labels: docs

#535 Fix typo in render-props.md
  docs/render-props.md
Labels: docs

#503 Bump bs-platform from 5.0.3 to 7.0.1
  lib/js/src/React.js
  lib/js/src/ReactDOMRe.js
  lib/js/src/ReactEvent.js
  lib/js/src/ReactEventRe.js
  lib/js/src/ReasonReact.js
  lib/js/src/ReasonReactRouter.js
  package.json
  yarn.lock
Labels: 0.8.0

#533 feat(SuspenseList): add React.SuspenseList
  lib/js/src/React.js
  src/React.re
Labels: 0.8.0, enhancement

#521 Simplify ref type
  src/React.re
  src/ReactDOMRe.re
Labels: 0.8.0

#399 Remove maxDuration prop from suspense
  src/React.re
Labels: 0.8.0

#520 Use Console.error instead of throwing so that ReactDOMRe doesn't import Caml_builtin_exceptions
  lib/js/src/ReactDOMRe.js
  src/ReactDOMRe.re
Labels: 0.8.0

#437 add unsafeAddStyle, define combine with external binding
  src/ReactDOMRe.re
Labels: 0.8.0

#526 `ReactEvent.relatedTarget` returns option
  src/ReactEvent.re
  src/ReactEvent.rei
Labels: 0.8.0, enhancement

#531 Add ReactEvent.Mouse.movementX and ReactEvent.Mouse.movementY
  src/ReactEvent.re
  src/ReactEvent.rei
Labels: 0.8.0, enhancement

#304 Add autoCapitalize #303
  src/ReactDOMRe.re
Labels: enhancement

#512 Add bindings for useTransition hook
  src/React.re
Labels: 0.8.0, enhancement

#281 set "min" property to "string"
  src/ReactDOMRe.re
Labels: 0.8.0

#361 Move react and react-dom into peerDependencies
  package.json
Labels: 0.8.0, enhancement

#433 Add binding for name and displayName
  src/React.re
Labels: enhancement

#519 Use an external for ReactDOMRE.Style.combine and remove Obj.magic
  lib/js/src/ReactDOMRe.js
  src/ReactDOMRe.re
Labels: 0.8.0, enhancement

#400 Add Unstable module that can render in concurrent mode
  lib/js/src/ReactDOMRe.js
  src/ReactDOMRe.re
  yarn.lock
Labels: 0.8.0

#244 Try ReasonReact at Repl.it
  docs/playground.md
Labels: docs

#534 [Docs] Updates to Installation, Intro, Additional Examples & Recipes
  docs/adding-data-props.md
  docs/gentype.md
  docs/installation.md
  docs/intro-example.md
  docs/simple.md
  docs/working-with-optional-data.md
  website/i18n/en.json
  website/pages/en/index.js
  website/sidebars.json
Labels: docs

#537 Add GraphQL & Apollo example
  docs/graphql-apollo.md
  website/i18n/en.json
  website/sidebars.json
Labels: docs

#539 Remove compilation warnings
  package.json
  src/React.re
  src/ReactDOMRe.re
  src/ReactDOMServerRe.re
  src/ReasonReact.re
  src/ReasonReactOptimizedCreateClass.re
  src/ReasonReactRouter.re
Labels: 0.8.0

#538 0.8.0 HISTORY/release notes
  HISTORY.md
Labels: 0.8.0

#542 Add additional explanations to first example.
  docs/simple.md
Labels: docs

#544 Docs: add information about using useState with form events
  docs/use-state-use-effect.md
  docs/usestate-event-value.md
  website/i18n/en.json
  website/sidebars.json
Labels: docs
