Repository reasonml/reason-react, pull requests merged in 2020-05, with the labels that each got.

#550 readme updates
  README.md
Labels: docs

#555 Fix Readme Bug and add youtube Videos
  README.md
Labels: docs

#552 Stop versioning lib/js
  .gitignore
  bsconfig.json
  lib/js/src/React.js
  lib/js/src/ReactDOMRe.js
  lib/js/src/ReactDOMServerRe.js
  lib/js/src/ReactEvent.js
  lib/js/src/ReactEventRe.js
  lib/js/src/ReasonReact.js
  lib/js/src/ReasonReactCompat.js
  lib/js/src/ReasonReactOptimizedCreateClass.js
  lib/js/src/ReasonReactRouter.js
  package.json
Labels: 0.9.0

#573 Docs: add explanation for how to import components with default props.
  docs/importing-js-into-reason.md
Labels: docs

#578 Move reason-test-framework to devDependency
  bsconfig.json
Labels: 0.9.0

#571 Adds React.component as a new binding for making components
  src/React.re
Labels: 0.9.0

#545 Use console.error for hydrate function
  src/ReactDOMRe.re
Labels: 0.9.0, enhancement

#586 Add Personas Avatar Generator to example projects
  docs/example-projects.md
Labels: docs

#547 RFC: ReactDOM simplification
  bsconfig.json
  lib/js/src/ReactDOM.js
  lib/js/src/ReactDOMServer.js
  lib/js/src/ReactDOMStyle.js
  lib/js/src/ReasonReactRouter.js
  lib/js/src/legacy/ReactDOMRe.js
  lib/js/src/legacy/ReactDOMServerRe.js
  lib/js/src/legacy/ReactEventRe.js
  lib/js/src/legacy/ReasonReact.js
  lib/js/src/legacy/ReasonReactCompat.js
  lib/js/src/legacy/ReasonReactOptimizedCreateClass.js
  package.json
  src/ReactDOM.re
  src/ReactDOMServer.re
  src/ReactDOMStyle.re
  src/legacy/ReactDOMRe.re
  src/legacy/ReactDOMServerRe.re
  src/legacy/ReactEventRe.re
  src/legacy/ReactEventRe.rei
  src/legacy/ReasonReact.re
  src/legacy/ReasonReact.rei
  src/legacy/ReasonReactCompat.re
  src/legacy/ReasonReactCompat.rei
  src/legacy/ReasonReactOptimizedCreateClass.re
  yarn.lock
Labels: 0.9.0, RFC

#546 RFC: use simpler constructs for createRoot
  src/legacy/ReactDOMRe.re
Labels: 0.9.0

#551 Add uncurried hooks
  src/React.re
Labels: 0.9.0
